name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yoheimuta/action-protolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: info
